### ISSUE TITLE
Port to React

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/core#26]
I believe this would be an important step in the correct direction, in terms of making it easier to maintain and contribute in the future, as well as keeping the line between the backend and frontend very clear.

It'll also give us an opportunity to start using ES6+ to write cleaner and more concise code.

A react + webpack (using `create-react-app`) would also streamline the produced assets and code in production. It should probably be done before it's too big a task.

I'm happy to kick this off in a fork/branch.

**Comment by bhajneet** [comment]
Started in dev branch -- Issue is too generic
