### ISSUE TITLE
Incorrect IP address

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/core#7]
169.254

https://askleo.com/why_cant_i_connect_with_a_169254xx_ip_address/

**Comment by bhajneet** [comment]
@bhajansweet now that we have "connect to" in the gui, can we close this issue and suggest users to find their IP address either manually or through the GUI? That should be good enough to close this issue.

**Comment by Harjot1Singh** [comment]
Why not display the hostname instead? It's not bound to an IP.

This is what I saw when I tested this earlier today. There is no port number however, which probably should be there.

**Comment by bhajneet** [comment]
The port number will be added in the future, good catch. It should be showing the active display's hostname in the titlebars of the navigator/display. Will check again to confirm later. 

I'm going to close this issue since we have a good alternative now. Please let me know, if you disagree, why it should be re-opened. Thank you.

**Comment by Harjot1Singh** [comment]
Agree that this can be closed, it did show my hostname.

I'm not convinced that the "Connect to" feature is that useful, since to use it, you'd have to install ShabadOS on the target, and at that point, you could just use the local installation anyway. It's also a manual action that has to be done every time someone starts it, whereas it's far more convenient to have a web browser window pointed to the display address loaded on startup.

**Comment by bhajneet** [comment]
The connect to is most useful for non-techies. I would think many gurdwaras probably don't have static IPs set up either, so another plus point there. It's just an additional option. Correct me if wrong, but I don't think any previous functionality was lost.

Another reason we went with the Connect To feature is that in the future we would like to use any open port, so we don't have to ask any non-techies to close an app that is using the same port. Then you wouldn't be able to automate the display address on startup unless we added another option, such as "Force this port number". Still doable, of course.

**Comment by Harjot1Singh** [comment]
Definitely no previous functionality lost. I don't think I'm articulating what I meant that clearly, but my understanding is:
1) The connect to feature is tied to a controller
2) If you've already got access to a controller, you'd probably just go ahead and use it without connecting
3) unless you wanted to sync some other screens somewhere else?

In the standalone mobile app scenario, I can see how this would be useful. However, to use the connect to right now, you'd have to access a controller, which is running on the ShabadOS server anyway, i.e. a shabadOS instance (1) is required to access another shabadOS instance (2), unless you just access it from a web browser? Surely I'd just use instance (1), and not bother with 2. 

It's not really a thing to change, but more an observation, and I'm trying to understand if I've overlooked a situation where I would actually use this. Are you able to outline the one that was in mind for this feature?

I do see the reasoning behind the open-port idea. I'm not sure what you mean by not displaying the address on startup though?

These are not really issues for the moment, but I think it's worth having a proper discussion/think about them for the long-run at some point.
